### ISSUE TITLE
RNG Cards

### ISSUE THREAD

**Issue by ficsby** [carloshurtadogil/BoardGame#4]
As a player I want a fair and clear way to determine the amount of steps taken on the board so I can have a a fair game and experience while playing

As a developer I want a unique and easy way to determine user movement throughout the board to offer a different yet clear experience to the user

Tasks: 
- Design cards
- Create a randomizer so that each card facing down has a unique value
- Save that value towards the character so that they can move in a certain direction

**Comment by carloshurtadogil** [comment]
NG cards are completed for now. In the next sprint, we'll attach them to players as to have them move the specified amount
